# Generated by Django 4.0.2 on 2022-03-26 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='videos',
        ),
    ]
